'use strict';

export const FAILED_RECEIVE_FORMS = 'FAILED_RECEIVE_FORMS';
export const FAILED_ADD_FORM = 'FAILED_CREATE_FORM';
export const FAILED_EDIT_FORM = 'FAILED_EDIT_FORM';
export const FAILED_DELETE_FORM = 'FAILED_DELETE_FORM';